// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdNG423THP_caJZfpwl3xK4dF-cb5UPcY',
    appId: '1:57969290708:web:ecc8e5b533658c782c7a41',
    messagingSenderId: '57969290708',
    projectId: 'flutter-project-6baf2',
    authDomain: 'flutter-project-6baf2.firebaseapp.com',
    storageBucket: 'flutter-project-6baf2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqOzW5x62ApeW_uc9ZNYZF2FOhexJnyOk',
    appId: '1:57969290708:android:a9d622a0ee18399c2c7a41',
    messagingSenderId: '57969290708',
    projectId: 'flutter-project-6baf2',
    storageBucket: 'flutter-project-6baf2.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdNG423THP_caJZfpwl3xK4dF-cb5UPcY',
    appId: '1:57969290708:web:f19761471e44b2de2c7a41',
    messagingSenderId: '57969290708',
    projectId: 'flutter-project-6baf2',
    authDomain: 'flutter-project-6baf2.firebaseapp.com',
    storageBucket: 'flutter-project-6baf2.appspot.com',
  );
}